// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package migrate

import (
	"flagon/internal/migrations"
	"flagon/pkg/database"
)

// Injectors from wire.go:

func New() (*CmdRunner, error) {
	db, err := database.Open()
	if err != nil {
		return nil, err
	}
	migrator, err := migrations.NewMigrations(db)
	if err != nil {
		return nil, err
	}
	cmdRunner := &CmdRunner{
		Migrator: migrator,
	}
	return cmdRunner, nil
}
