// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"flagon/internal/api/v1"
	"flagon/internal/repository"
	"flagon/internal/server"
	"flagon/internal/service"
	"flagon/pkg/cache"
	"flagon/pkg/database"
)

// Injectors from wire.go:

func New() (*CmdRunner, error) {
	db, err := database.Open()
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(db)
	redisCache, err := cache.New()
	if err != nil {
		return nil, err
	}
	tokenRepository := repository.NewTokenRepository(redisCache)
	authService := service.NewAuthService(userRepository, tokenRepository)
	authAPI := v1.NewAuthAPI(authService, tokenRepository)
	api := v1.New(authAPI)
	httpServer, err := server.NewHttpServer(api)
	if err != nil {
		return nil, err
	}
	cmdRunner := &CmdRunner{
		HttpServer: httpServer,
	}
	return cmdRunner, nil
}
